import time
import os

os.system("cls")
print()
print("\t\t\t시를 감상합시다\n")
print("\t\t1. 시1~~~~~~~~~\n")
print("\t\t2. 시2~~~~~~~~~\n")
print("\t\t3. 시3~~~~~~~~~\n")
print("\t\t4. 종 료")

menunumber = input("감상하려는 시의 번호를 입력하세요 : ")

while menunumber != "4":
    print("\n" * 40)
    if menunumber == "1":
        print("\t1번 시 1번 시 1번 시 1번 시 1번 시")
        time.sleep(1)
        print("\t1번 시 1번 시 1번 시 1번 시 1번 시")
        time.sleep(1)
        print("\t1번 시 1번 시 1번 시 1번 시 1번 시")
        time.sleep(1)
        print("\t1번 시 1번 시 1번 시 1번 시 1번 시")
        time.sleep(1)
        print("\t1번 시 1번 시 1번 시 1번 시 1번 시")
        time.sleep(1)
        print("\t1번 시 1번 시 1번 시 1번 시 1번 시")
        time.sleep(1)
        print("\t1번 시 1번 시 1번 시 1번 시 1번 시")
        time.sleep(1)
        input("감상이 끝났으면 아무키나 누르세요")

    elif menunumber == "2":
        print("\t2번 시 2번 시 2번 시 2번 시 2번 시")
        time.sleep(1)
        print("\t2번 시 2번 시 2번 시 2번 시 2번 시")
        time.sleep(1)
        print("\t2번 시 2번 시 2번 시 2번 시 2번 시")
        time.sleep(1)
        print("\t2번 시 2번 시 2번 시 2번 시 2번 시")
        time.sleep(1)
        print("\t2번 시 2번 시 2번 시 2번 시 2번 시")
        time.sleep(1)
        print("\t2번 시 2번 시 2번 시 2번 시 2번 시")
        time.sleep(1)
        print("\t2번 시 2번 시 2번 시 2번 시 2번 시")
        time.sleep(1)
        print("\t2번 시 2번 시 2번 시 2번 시 2번 시")
        time.sleep(1)
        input("감상이 끝났으면 아무키나 누르세요")

    elif menunumber == "3":
        print("\t3번 시 3번 시 3번 시 3번 시 3번 시")
        time.sleep(1)
        print("\t3번 시 3번 시 3번 시 3번 시 3번 시")
        time.sleep(1)
        print("\t3번 시 3번 시 3번 시 3번 시 3번 시")
        time.sleep(1)
        print("\t3번 시 3번 시 3번 시 3번 시 3번 시")
        time.sleep(1)
        print("\t3번 시 3번 시 3번 시 3번 시 3번 시")
        time.sleep(1)
        print("\t3번 시 3번 시 3번 시 3번 시 3번 시")
        time.sleep(1)
        print("\t3번 시 3번 시 3번 시 3번 시 3번 시")
        time.sleep(1)
        print("\t3번 시 3번 시 3번 시 3번 시 3번 시")
        time.sleep(1)
        input("감상이 끝났으면 아무키나 누르세요")

    else:
        print("이 프로그램의 사용법은 ....")
        print("이 프로그램의 사용법은 ....")
        print("이 프로그램의 사용법은 ....")
        print("이 프로그램의 사용법은 ....")
        print("이 프로그램의 사용법은 ....")

    print()
    print("\t\t\t시를 감상합시다\n")
    print("\t\t1. 시1~~~~~~~~~\n")
    print("\t\t2. 시2~~~~~~~~~\n")
    print("\t\t3. 시3~~~~~~~~~\n")
    print("\t\t4. 종 료")

    menunumber = input("감상하려는 시의 번호를 입력하세요 : ")

print("안녕히 가세요")